# Generated by Django 3.1.2 on 2020-12-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('lead_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('reference', models.CharField(max_length=25)),
                ('product', models.CharField(max_length=25)),
                ('loan_amt', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='by_online',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='mapped_to',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='mapped_to_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
