# Generated by Django 3.1.2 on 2020-12-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201230_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
