# Generated by Django 3.1.2 on 2021-01-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210103_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mapped_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='reference',
            field=models.CharField(max_length=50),
        ),
    ]
