# Generated by Django 3.1.2 on 2021-01-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210104_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='added_by',
            new_name='id',
        ),
    ]
