# Generated by Django 3.1.2 on 2021-01-04 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210104_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
