# Generated by Django 3.1.2 on 2021-01-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210104_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='id',
            new_name='added_by',
        ),
    ]
