# Generated by Django 3.1.2 on 2021-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210104_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
    ]
