# Generated by Django 3.1.2 on 2021-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210413_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agreement',
            field=models.FileField(default='terms.pdf', upload_to='agreements'),
        ),
    ]
