# Generated by Django 3.1.2 on 2021-04-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_customuser_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='degree_others',
        ),
    ]
