# Generated by Django 3.1.2 on 2021-04-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_personaldetails_degree_others'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='lawyerType',
        ),
    ]
