# Generated by Django 3.1.2 on 2021-04-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=25)),
                ('cust_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('cost_particular_id', models.AutoField(primary_key=True, serialize=False)),
                ('particulars', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('remark_id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StageOfConstruction',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('romm_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('prop_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop_type', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('builder_cat', models.CharField(max_length=25)),
                ('occupation_certi', models.CharField(max_length=25)),
                ('prev_agreement', models.CharField(max_length=25)),
                ('sub_scheme', models.CharField(max_length=25)),
                ('perc_completion', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetailsROI',
            fields=[
                ('oth_det_roi_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_val', models.IntegerField()),
                ('max_val', models.IntegerField()),
                ('roi', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('oth_det_id', models.AutoField(primary_key=True, serialize=False)),
                ('prevailing_rate', models.IntegerField()),
                ('tenure', models.CharField(max_length=25)),
                ('inward_cheque_return', models.CharField(max_length=25)),
                ('multiple_inquiry', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('obligation_id', models.AutoField(primary_key=True, serialize=False)),
                ('emi_oblig', models.CharField(max_length=25)),
                ('emi_oblig_not_consi', models.CharField(max_length=25)),
                ('credit_card', models.CharField(max_length=25)),
                ('credit_card_oblig_percent', models.IntegerField()),
                ('gold_loan', models.CharField(max_length=25)),
                ('gold_loan_percent', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeEmployerProfile',
            fields=[
                ('neg_emp_pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('neg_emp_pro', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='LoanTowardsValuation',
            fields=[
                ('loan_tow_val_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_sheet', models.CharField(max_length=90)),
                ('amount', models.IntegerField()),
                ('rbi_guidelines', models.CharField(max_length=25)),
                ('ammenity', models.CharField(max_length=25)),
                ('additional', models.CharField(max_length=25)),
                ('car_parking', models.CharField(max_length=25)),
                ('car_parking_percent', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAmount',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_loan_amt', models.IntegerField()),
                ('max_loan_amt', models.IntegerField()),
                ('total_Exp', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeFoir',
            fields=[
                ('inc_foir_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_amt', models.IntegerField()),
                ('max_amt', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('gross_sal', models.CharField(max_length=25)),
                ('net_sal', models.CharField(max_length=25)),
                ('bonus', models.CharField(max_length=25)),
                ('bonus_avg_yearly', models.CharField(max_length=25)),
                ('bonus_avg_yearly_percent', models.CharField(max_length=25)),
                ('bonus_avg_qtr', models.CharField(max_length=25)),
                ('bonus_avg_qtr_percent', models.CharField(max_length=25)),
                ('bonus_avg_half_yearly', models.CharField(max_length=25)),
                ('bonus_avg_half_yearly_percent', models.CharField(max_length=25)),
                ('rent_income', models.CharField(max_length=25)),
                ('rent_agreement_type', models.CharField(max_length=25)),
                ('bank_ref', models.CharField(max_length=25)),
                ('rent_ref_in_bank', models.CharField(max_length=25)),
                ('rent_inc_percent', models.CharField(max_length=25)),
                ('fut_rent', models.CharField(max_length=25)),
                ('fut_rent_percent', models.CharField(max_length=25)),
                ('incentive', models.CharField(max_length=25)),
                ('incen_avg_months', models.CharField(max_length=25)),
                ('incen_percent', models.CharField(max_length=25)),
                ('coApplicant_No_Income_only_Rent_income', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_fees', models.CharField(max_length=25)),
                ('proc_fee_app', models.CharField(max_length=25)),
                ('proc_fee_type', models.CharField(max_length=25)),
                ('proc_fee_flat_loan_amtwise', models.CharField(max_length=25)),
                ('proc_fee_percent_loan_amtwise', models.CharField(max_length=25)),
                ('offers', models.CharField(max_length=25)),
                ('offline_or_online', models.CharField(max_length=7)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNationality',
            fields=[
                ('cust_nat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_nat', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDesignation',
            fields=[
                ('cust_desig_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_desig', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_age', models.IntegerField()),
                ('total_Exp', models.IntegerField()),
                ('form16', models.CharField(max_length=3)),
                ('salary_type', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_type', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Cibil',
            fields=[
                ('cibil_id', models.AutoField(primary_key=True, serialize=False)),
                ('cibil_range_min', models.IntegerField()),
                ('cibil_range_max', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('age_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_age', models.IntegerField()),
                ('retire_age', models.IntegerField()),
                ('max_age_consi_others', models.IntegerField()),
                ('max_age_consi_gov', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
    ]
