# Generated by Django 3.1.2 on 2021-04-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AYYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay_year', models.CharField(max_length=7)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=30)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_type', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desg_type', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_source', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=10)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_business', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_in', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_type', models.CharField(max_length=45)),
                ('rejection_reason', models.CharField(max_length=60)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageOfConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=55)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_product', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.product')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.state')),
            ],
        ),
    ]
